In [41]:
import numpy as np

In [42]:
import pandas as pd

In [43]:
file=pd.read_csv('job_descriptions.csv')

In [44]:
file.head()

,Job Id,Experience,Qualifications,Salary Range,location,Country,latitude,longitude,Work Type,Company Size,...,Contact,Job Title,Role,Job Portal,Job Description,Benefits,skills,Responsibilities,Company,Company Profile
0,1089843540111562,5 to 15 Years,M.Tech,$59K-$99K,Douglas,Isle of Man,54.2361,-4.5481,Intern,26801,...,001-381-930-7517x737,Digital Marketing Specialist,Social Media Manager,Snagajob,Social Media Managers oversee an organizations...,"{'Flexible Spending Accounts (FSAs), Relocatio...","Social media platforms (e.g., Facebook, Twitte...","Manage and grow social media accounts, create ...",Icahn Enterprises,"{""Sector"":""Diversified"",""Industry"":""Diversifie..."
1,398454096642776,2 to 12 Years,BCA,$56K-$116K,Ashgabat,Turkmenistan,38.9697,59.5563,Intern,100340,...,461-509-4216,Web Developer,Frontend Web Developer,Idealist,Frontend Web Developers design and implement u...,"{'Health Insurance, Retirement Plans, Paid Tim...","HTML, CSS, JavaScript Frontend frameworks (e.g...","Design and code user interfaces for websites, ...",PNC Financial Services Group,"{""Sector"":""Financial Services"",""Industry"":""Com..."
2,481640072963533,0 to 12 Years,PhD,$61K-$104K,Macao,"Macao SAR, China",22.1987,113.5439,Temporary,84525,...,9687619505,Operations Manager,Quality Control Manager,Jobs2Careers,Quality Control Managers establish and enforce...,"{'Legal Assistance, Bonuses and Incentive Prog...",Quality control processes and methodologies St...,Establish and enforce quality control standard...,United Services Automobile Assn.,"{""Sector"":""Insurance"",""Industry"":""Insurance: P..."
3,688192671473044,4 to 11 Years,PhD,$65K-$91K,Porto-Novo,Benin,9.3077,2.3158,Full-Time,129896,...,+1-820-643-5431x47576,Network Engineer,Wireless Network Engineer,FlexJobs,"Wireless Network Engineers design, implement, ...","{'Transportation Benefits, Professional Develo...",Wireless network design and architecture Wi-Fi...,"Design, configure, and optimize wireless netwo...",Hess,"{""Sector"":""Energy"",""Industry"":""Mining, Crude-O..."
4,117057806156508,1 to 12 Years,MBA,$64K-$87K,Santiago,Chile,-35.6751,-71.5429,Intern,53944,...,343.975.4702x9340,Event Manager,Conference Manager,Jobs2Careers,A Conference Manager coordinates and manages c...,"{'Flexible Spending Accounts (FSAs), Relocatio...",Event planning Conference logistics Budget man...,Specialize in conference and convention planni...,Cairn Energy,"{""Sector"":""Energy"",""Industry"":""Energy - Oil & ..."

In [45]:
file['Experience']

0          5 to 15 Years
1          2 to 12 Years
2          0 to 12 Years
3          4 to 11 Years
4          1 to 12 Years
               ...
1615935    0 to 12 Years
1615936    2 to 14 Years
1615937    4 to 15 Years
1615938    5 to 15 Years
1615939    1 to 11 Years
Name: Experience, Length: 1615940, dtype: object

In [46]:
t=file['Experience'].str.split()

In [47]:
t

0          [5, to, 15, Years]
1          [2, to, 12, Years]
2          [0, to, 12, Years]
3          [4, to, 11, Years]
4          [1, to, 12, Years]
                  ...
1615935    [0, to, 12, Years]
1615936    [2, to, 14, Years]
1615937    [4, to, 15, Years]
1615938    [5, to, 15, Years]
1615939    [1, to, 11, Years]
Name: Experience, Length: 1615940, dtype: object

In [48]:
acc=[]
for i in t:
    acc.append(i[0])

In [49]:
bcc=[]
for i in t:
    bcc.append(i[2])

In [50]:
acc

['5',
 '2',
 '0',
 '4',
 '1',
 '4',
 '3',
 '2',
 '2',
 '1',
 '3',
 '4',
 '3',
 '1',
 '1',
 '4',
 '5',
 '0',
 '3',
 '5',
 '0',
 '0',
 '1',
 '2',
 '3',
 '4',
 '5',
 '4',
 '0',
 '2',
 '4',
 '3',
 '1',
 '1',
 '0',
 '3',
 '0',
 '0',
 '4',
 '5',
 '5',
 '2',
 '4',
 '0',
 '1',
 '1',
 '3',
 '5',
 '3',
 '4',
 '5',
 '4',
 '4',
 '5',
 '0',
 '5',
 '4',
 '4',
 '2',
 '2',
 '3',
 '5',
 '0',
 '1',
 '4',
 '0',
 '4',
 '3',
 '1',
 '0',
 '3',
 '5',
 '5',
 '2',
 '1',
 '1',
 '1',
 '4',
 '4',
 '2',
 '4',
 '1',
 '4',
 '4',
 '1',
 '5',
 '0',
 '0',
 '5',
 '2',
 '2',
 '2',
 '2',
 '2',
 '1',
 '1',
 '1',
 '4',
 '4',
 '1',
 '5',
 '4',
 '0',
 '0',
 '0',
 '1',
 '5',
 '4',
 '1',
 '0',
 '3',
 '4',
 '5',
 '5',
 '4',
 '2',
 '3',
 '3',
 '0',
 '4',
 '2',
 '2',
 '2',
 '5',
 '4',
 '0',
 '1',
 '2',
 '0',
 '2',
 '4',
 '0',
 '1',
 '5',
 '1',
 '0',
 '4',
 '3',
 '4',
 '0',
 '2',
 '1',
 '3',
 '3',
 '2',
 '0',
 '5',
 '2',
 '5',
 '5',
 '1',
 '0',
 '4',
 '2',
 '5',
 '2',
 '3',
 '5',
 '1',
 '4',
 '3',
 '2',
 '1',
 '0',
 '2',
 '1',
 '5',
 '0',
 '2',
 '2',
 '3',
 '2',
 '1',
 '2',
 '1',
 '1',
 '1',
 '4',
 '2',
 '1',
 '3',
 '2',
 '5',
 '4',
 '1',
 '3',
 '3',
 '3',
 '1',
 '2',
 '3',
 '2',
 '0',
 '1',
 '3',
 '1',
 '5',
 '1',
 '4',
 '0',
 '3',
 '2',
 '0',
 '3',
 '4',
 '5',
 '2',
 '3',
 '2',
 '5',
 '3',
 '1',
 '5',
 '1',
 '5',
 '3',
 '2',
 '5',
 '5',
 '4',
 '4',
 '5',
 '5',
 '1',
 '3',
 '4',
 '5',
 '2',
 '1',
 '3',
 '2',
 '0',
 '4',
 '0',
 '5',
 '5',
 '3',
 '1',
 '5',
 '4',
 '0',
 '1',
 '1',
 '1',
 '0',
 '3',
 '4',
 '1',
 '0',
 '1',
 '0',
 '0',
 '2',
 '0',
 '2',
 '0',
 '1',
 '2',
 '5',
 '5',
 '2',
 '1',
 '2',
 '0',
 '4',
 '5',
 '4',
 '2',
 '4',
 '3',
 '4',
 '2',
 '5',
 '2',
 '2',
 '4',
 '1',
 '2',
 '3',
 '0',
 '0',
 '4',
 '1',
 '0',
 '5',
 '4',
 '0',
 '2',
 '0',
 '2',
 '2',
 '2',
 '4',
 '4',
 '5',
 '5',
 '3',
 '2',
 '4',
 '1',
 '5',
 '5',
 '0',
 '0',
 '4',
 '0',
 '0',
 '3',
 '4',
 '3',
 '1',
 '1',
 '0',
 '5',
 '0',
 '3',
 '5',
 '1',
 '2',
 '1',
 '5',
 '5',
 '5',
 '0',
 '5',
 '2',
 '1',
 '0',
 '4',
 '1',
 '3',
 '5',
 '0',
 '4',
 '4',
 '0',
 '2',
 '5',
 '2',
 '3',
 '4',
 '4',
 '3',
 '3',
 '4',
 '0',
 '3',
 '2',
 '3',
 '4',
 '2',
 '2',
 '1',
 '0',
 '1',
 '4',
 '0',
 '5',
 '0',
 '5',
 '5',
 '3',
 '0',
 '4',
 '4',
 '4',
 '0',
 '5',
 '1',
 '2',
 '5',
 '3',
 '3',
 '1',
 '0',
 '1',
 '3',
 '1',
 '1',
 '5',
 '0',
 '3',
 '4',
 '4',
 '4',
 '4',
 '2',
 '3',
 '5',
 '1',
 '5',
 '2',
 '3',
 '2',
 '1',
 '3',
 '0',
 '2',
 '3',
 '2',
 '0',
 '5',
 '1',
 '2',
 '3',
 '5',
 '1',
 '4',
 '5',
 '4',
 '1',
 '5',
 '0',
 '2',
 '5',
 '0',
 '5',
 '2',
 '2',
 '2',
 '3',
 '2',
 '0',
 '3',
 '5',
 '0',
 '4',
 '1',
 '4',
 '0',
 '0',
 '4',
 '4',
 '5',
 '0',
 '0',
 '4',
 '4',
 '5',
 '2',
 '2',
 '3',
 '3',
 '3',
 '0',
 '0',
 '4',
 '3',
 '1',
 '5',
 '1',
 '0',
 '1',
 '3',
 '2',
 '1',
 '2',
 '5',
 '2',
 '3',
 '0',
 '1',
 '0',
 '5',
 '4',
 '1',
 '1',
 '1',
 '3',
 '2',
 '5',
 '4',
 '1',
 '3',
 '4',
 '5',
 '2',
 '1',
 '3',
 '2',
 '5',
 '0',
 '3',
 '5',
 '4',
 '1',
 '0',
 '4',
 '1',
 '1',
 '5',
 '2',
 '0',
 '0',
 '1',
 '2',
 '1',
 '1',
 '3',
 '4',
 '2',
 '5',
 '2',
 '0',
 '0',
 '2',
 '3',
 '2',
 '1',
 '4',
 '4',
 '0',
 '5',
 '2',
 '2',
 '5',
 '1',
 '5',
 '2',
 '2',
 '4',
 '1',
 '4',
 '0',
 '4',
 '0',
 '3',
 '0',
 '4',
 '0',
 '0',
 '0',
 '5',
 '1',
 '5',
 '5',
 '3',
 '4',
 '3',
 '0',
 '2',
 '1',
 '1',
 '0',
 '0',
 '0',
 '5',
 '3',
 '5',
 '4',
 '5',
 '5',
 '4',
 '5',
 '1',
 '1',
 '3',
 '1',
 '5',
 '5',
 '4',
 '5',
 '1',
 '5',
 '0',
 '5',
 '1',
 '1',
 '3',
 '5',
 '2',
 '0',
 '5',
 '2',
 '3',
 '0',
 '0',
 '1',
 '3',
 '5',
 '2',
 '4',
 '2',
 '1',
 '5',
 '3',
 '2',
 '2',
 '4',
 '1',
 '0',
 '3',
 '1',
 '3',
 '5',
 '1',
 '4',
 '3',
 '0',
 '0',
 '1',
 '5',
 '3',
 '2',
 '1',
 '2',
 '2',
 '4',
 '1',
 '4',
 '1',
 '4',
 '5',
 '1',
 '5',
 '3',
 '5',
 '0',
 '5',
 '5',
 '5',
 '2',
 '2',
 '2',
 '1',
 '4',
 '0',
 '4',
 '2',
 '3',
 '4',
 '5',
 '2',
 '2',
 '5',
 '3',
 '4',
 '4',
 '2',
 '4',
 '4',
 '0',
 '0',
 '2',
 '5',
 '2',
 '5',
 '0',
 '0',
 '0',
 '2',
 '0',
 '5',
 '3',
 '1',
 '3',
 '4',
 '1',
 '5',
 '5',
 '4',
 '1',
 '3',
 '5',
 '1',
 '3',
 '5',
 '5',
 '0',
 '4',
 '5',
 '4',
 '5',
 '2',
 '2',
 '4',
 '5',
 '4',
 '5',
 '1',
 '0',
 '3',
 '4',
 '1',
 '2',
 '5',
 '2',
 '0',
 '4',
 '0',
 '1',
 '5',
 '1',
 '1',
 '5',
 '0',
 '2',
 '0',
 '1',
 '2',
 '5',
 '4',
 '5',
 '4',
 '2',
 '1',
 '2',
 '1',
 '3',
 '5',
 '4',
 '2',
 '0',
 '1',
 '3',
 '1',
 '1',
 '1',
 '4',
 '2',
 '5',
 '4',
 '3',
 '4',
 '4',
 '1',
 '3',
 '5',
 '1',
 '2',
 '3',
 '0',
 '3',
 '0',
 '1',
 '4',
 '1',
 '5',
 '1',
 '4',
 '5',
 '5',
 '0',
 '0',
 '1',
 '1',
 '5',
 '1',
 '5',
 '0',
 '0',
 '1',
 '1',
 '1',
 '5',
 '0',
 '1',
 '0',
 '2',
 '5',
 '3',
 '1',
 '1',
 '2',
 '2',
 '4',
 '2',
 '4',
 '0',
 '5',
 '0',
 '1',
 '2',
 '3',
 '4',
 '1',
 '3',
 '0',
 '5',
 '2',
 '2',
 '1',
 '5',
 '3',
 '1',
 '3',
 '5',
 '0',
 '1',
 '2',
 '5',
 '5',
 '0',
 '4',
 '0',
 '1',
 '2',
 '5',
 '2',
 '2',
 '0',
 '5',
 '5',
 '5',
 '5',
 '1',
 '5',
 '3',
 '5',
 '5',
 '1',
 '5',
 '4',
 '2',
 '0',
 '2',
 '4',
 '1',
 '4',
 '1',
 '4',
 '4',
 '5',
 '1',
 '0',
 '3',
 '4',
 '4',
 '5',
 '1',
 '2',
 '1',
 '5',
 '1',
 '1',
 '4',
 '4',
 '4',
 '2',
 '5',
 '3',
 '3',
 '5',
 '1',
 '3',
 '3',
 '3',
 '1',
 '0',
 '5',
 '4',
 '1',
 '0',
 '2',
 '2',
 '4',
 '4',
 '4',
 '4',
 '2',
 '5',
 '5',
 '2',
 '2',
 '0',
 '3',
 '4',
 '4',
 '0',
 '0',
 '3',
 '0',
 '4',
 '5',
 '5',
 '5',
 '5',
 '1',
 '1',
 '3',
 '0',
 '1',
 '5',
 '4',
 '3',
 '2',
 '0',
 '2',
 '0',
 '2',
 '1',
 '3',
 '5',
 '3',
 '1',
 '3',
 '2',
 '0',
 '3',
 '4',
 '4',
 '2',
 '1',
 '0',
 '1',
 '3',
 '3',
 '0',
 '4',
 '2',
 '2',
 '5',
 '4',
 '5',
 '3',
 '2',
 '2',
 '0',
 '1',
 '1',
 '3',
 '5',
 '1',
 '0',
 '3',
 '2',
 '0',
 '2',
 '0',
 '2',
 '4',
 '4',
 '4',
 '5',
 '4',
 '2',
 '5',
 '3',
 '0',
 '3',
 '0',
 '3',
 '0',
 '3',
 '3',
 '5',
 '1',
 '0',
 '0',
 '2',
 '2',
 '1',
 '4',
 '5',
 '3',
 '0',
 '4',
 '0',
 '1',
 '2',
 '2',
 '1',
 '1',
 '0',
 '5',
 '0',
 '1',
 '1',
 '1',
 '1',
 '4',
 '0',
 '2',
 '1',
 '2',
 '1',
 '5',
 '2',
 '4',
 '2',
 '5',
 '4',
 '1',
 '1',
 '1',
 '4',
 '0',
 '1',
 '3',
 '5',
 '4',
 '2',
 '1',
 '2',
 '3',
 '2',
 '4',
 '3',
 '4',
 '3',
 ...]

In [51]:
file['upperbexperience']=bcc

In [52]:
file['lowerbexperience']=acc

In [53]:
file.to_csv('jobdata2.csv')

In [54]:
rf=pd.read_csv('jobdata2.csv')

In [55]:
rf

,Unnamed: 0,Job Id,Experience,Qualifications,Salary Range,location,Country,latitude,longitude,Work Type,...,Role,Job Portal,Job Description,Benefits,skills,Responsibilities,Company,Company Profile,upperbexperience,lowerbexperience
0,0,1089843540111562,5 to 15 Years,M.Tech,$59K-$99K,Douglas,Isle of Man,54.2361,-4.5481,Intern,...,Social Media Manager,Snagajob,Social Media Managers oversee an organizations...,"{'Flexible Spending Accounts (FSAs), Relocatio...","Social media platforms (e.g., Facebook, Twitte...","Manage and grow social media accounts, create ...",Icahn Enterprises,"{""Sector"":""Diversified"",""Industry"":""Diversifie...",15,5
1,1,398454096642776,2 to 12 Years,BCA,$56K-$116K,Ashgabat,Turkmenistan,38.9697,59.5563,Intern,...,Frontend Web Developer,Idealist,Frontend Web Developers design and implement u...,"{'Health Insurance, Retirement Plans, Paid Tim...","HTML, CSS, JavaScript Frontend frameworks (e.g...","Design and code user interfaces for websites, ...",PNC Financial Services Group,"{""Sector"":""Financial Services"",""Industry"":""Com...",12,2
2,2,481640072963533,0 to 12 Years,PhD,$61K-$104K,Macao,"Macao SAR, China",22.1987,113.5439,Temporary,...,Quality Control Manager,Jobs2Careers,Quality Control Managers establish and enforce...,"{'Legal Assistance, Bonuses and Incentive Prog...",Quality control processes and methodologies St...,Establish and enforce quality control standard...,United Services Automobile Assn.,"{""Sector"":""Insurance"",""Industry"":""Insurance: P...",12,0
3,3,688192671473044,4 to 11 Years,PhD,$65K-$91K,Porto-Novo,Benin,9.3077,2.3158,Full-Time,...,Wireless Network Engineer,FlexJobs,"Wireless Network Engineers design, implement, ...","{'Transportation Benefits, Professional Develo...",Wireless network design and architecture Wi-Fi...,"Design, configure, and optimize wireless netwo...",Hess,"{""Sector"":""Energy"",""Industry"":""Mining, Crude-O...",11,4
4,4,117057806156508,1 to 12 Years,MBA,$64K-$87K,Santiago,Chile,-35.6751,-71.5429,Intern,...,Conference Manager,Jobs2Careers,A Conference Manager coordinates and manages c...,"{'Flexible Spending Accounts (FSAs), Relocatio...",Event planning Conference logistics Budget man...,Specialize in conference and convention planni...,Cairn Energy,"{""Sector"":""Energy"",""Industry"":""Energy - Oil & ...",12,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1615935,1615935,134563577088850,0 to 12 Years,B.Tech,$64K-$114K,"Malabo (de jure),",Equatorial Guinea,1.6508,10.2679,Full-Time,...,Mechanical Design Engineer,ZipRecruiter,Mechanical Design Engineers create and develop...,"{'Employee Assistance Programs (EAP), Tuition ...","Mechanical engineering CAD software (e.g., Sol...","Design mechanical systems, components, and pro...",The Hershey Company,"{""Sector"":""Food and Beverage/Confectionery"",""I...",12,0
1615936,1615936,618604818190827,2 to 14 Years,M.Tech,$62K-$130K,Warsaw,Poland,51.9194,19.1451,Intern,...,IT Director,USAJOBS,An IT Director oversees an organizations IT de...,"{'Health Insurance, Retirement Plans, Paid Tim...",Strategic IT planning Leadership and managemen...,Provide strategic leadership for IT department...,EQT,"{""Sector"":""Energy"",""Industry"":""Energy"",""City"":...",14,2
1615937,1615937,615471367712200,4 to 15 Years,BCA,$60K-$96K,Ashgabat,Turkmenistan,38.9697,59.5563,Part-Time,...,Mechanical Design Engineer,Indeed,Mechanical Design Engineers create and develop...,"{'Tuition Reimbursement, Stock Options or Equi...","Mechanical engineering CAD software (e.g., Sol...","Design mechanical systems, components, and pro...",KLA,"{""Sector"":""Technology"",""Industry"":""Semiconduct...",15,4
1615938,1615938,804137342023945,5 to 15 Years,BCA,$65K-$103K,Ouagadougou,Burkina Faso,12.2383,-1.5616,Full-Time,...,Training Coordinator,Stack Overflow Jobs,Training Coordinators design and implement emp...,"{'Casual Dress Code, Social and Recreational A...",Training program coordination Training materia...,"Coordinate employee training programs, track t...",Mahindra & Mahindra,"{""Sector"":""Automotive"",""Industry"":""Automotive""...",15,5
1615939,1615939,404645755314484,1 to 11 Years,BBA,$56K-$109K,Asmara,Eritrea,15.1794,39.7823,Part-Time,...,Wedding Planner,USAJOBS,Wedding Planners specialize in organizing wedd...,"{'Transportation Benefits, Professional Develo...",Wedding planning Venue selection Catering and ...,"Specialize in wedding planning, assisting coup...",Ashtead Group,"{""Sector"":""Equipment Rental"",""Industry"":""Equip...",11,1

In [56]:
rf['Country']

0                Isle of Man
1               Turkmenistan
2           Macao SAR, China
3                      Benin
4                      Chile
                 ...
1615935    Equatorial Guinea
1615936               Poland
1615937         Turkmenistan
1615938         Burkina Faso
1615939              Eritrea
Name: Country, Length: 1615940, dtype: object

In [57]:
rf['Salary Range']

0           $59K-$99K
1          $56K-$116K
2          $61K-$104K
3           $65K-$91K
4           $64K-$87K
              ...
1615935    $64K-$114K
1615936    $62K-$130K
1615937     $60K-$96K
1615938    $65K-$103K
1615939    $56K-$109K
Name: Salary Range, Length: 1615940, dtype: object

In [58]:
t=file['Salary Range'].str.split('-')
tg=[]
for i in t:
    tg.append(i[0])
for i in range(len(tg)):
    tg[i]=int(tg[i][1:-1])
tg

[59,
 56,
 61,
 65,
 64,
 59,
 63,
 65,
 65,
 60,
 57,
 64,
 65,
 56,
 57,
 65,
 60,
 55,
 55,
 65,
 62,
 64,
 58,
 62,
 60,
 58,
 59,
 64,
 63,
 65,
 55,
 65,
 57,
 65,
 62,
 58,
 60,
 64,
 57,
 58,
 56,
 55,
 62,
 65,
 56,
 59,
 56,
 64,
 59,
 57,
 62,
 55,
 59,
 59,
 64,
 60,
 63,
 57,
 65,
 65,
 61,
 57,
 56,
 65,
 65,
 55,
 59,
 63,
 64,
 56,
 64,
 58,
 56,
 65,
 64,
 60,
 55,
 56,
 63,
 55,
 61,
 56,
 65,
 57,
 63,
 59,
 65,
 56,
 55,
 61,
 58,
 60,
 57,
 64,
 58,
 61,
 55,
 58,
 58,
 59,
 63,
 55,
 62,
 61,
 64,
 59,
 64,
 61,
 62,
 64,
 59,
 56,
 60,
 60,
 61,
 65,
 65,
 65,
 63,
 64,
 63,
 55,
 63,
 56,
 60,
 60,
 60,
 55,
 62,
 58,
 55,
 59,
 65,
 57,
 65,
 57,
 56,
 62,
 56,
 56,
 61,
 60,
 58,
 60,
 63,
 55,
 56,
 61,
 60,
 62,
 63,
 61,
 56,
 60,
 63,
 65,
 59,
 58,
 61,
 62,
 59,
 59,
 65,
 60,
 65,
 59,
 65,
 63,
 56,
 59,
 56,
 59,
 60,
 56,
 59,
 60,
 65,
 62,
 62,
 57,
 56,
 55,
 61,
 64,
 65,
 63,
 61,
 63,
 55,
 56,
 55,
 57,
 56,
 61,
 59,
 61,
 62,
 61,
 57,
 59,
 57,
 57,
 59,
 63,
 60,
 56,
 57,
 62,
 57,
 57,
 64,
 56,
 55,
 61,
 62,
 64,
 65,
 57,
 55,
 59,
 56,
 59,
 60,
 56,
 62,
 55,
 56,
 64,
 59,
 62,
 56,
 61,
 65,
 57,
 63,
 60,
 56,
 63,
 61,
 56,
 56,
 55,
 60,
 62,
 62,
 55,
 55,
 59,
 56,
 56,
 63,
 64,
 61,
 64,
 60,
 65,
 58,
 60,
 55,
 56,
 63,
 59,
 62,
 60,
 65,
 55,
 63,
 55,
 59,
 63,
 57,
 58,
 55,
 55,
 57,
 56,
 59,
 59,
 65,
 64,
 59,
 57,
 58,
 60,
 56,
 61,
 64,
 59,
 63,
 58,
 64,
 55,
 60,
 55,
 55,
 59,
 64,
 64,
 57,
 62,
 61,
 59,
 65,
 62,
 57,
 56,
 61,
 59,
 63,
 64,
 63,
 62,
 61,
 61,
 61,
 64,
 55,
 59,
 59,
 60,
 60,
 58,
 56,
 60,
 64,
 60,
 57,
 62,
 55,
 55,
 56,
 61,
 63,
 58,
 65,
 57,
 55,
 57,
 61,
 60,
 57,
 59,
 61,
 57,
 63,
 64,
 62,
 64,
 59,
 58,
 55,
 56,
 62,
 61,
 63,
 62,
 59,
 55,
 56,
 59,
 60,
 60,
 55,
 55,
 61,
 64,
 56,
 58,
 57,
 59,
 63,
 65,
 64,
 56,
 59,
 65,
 58,
 65,
 56,
 59,
 62,
 58,
 63,
 60,
 64,
 57,
 56,
 59,
 55,
 57,
 56,
 58,
 65,
 62,
 58,
 63,
 60,
 56,
 65,
 57,
 57,
 60,
 60,
 57,
 65,
 60,
 62,
 59,
 56,
 62,
 57,
 56,
 65,
 62,
 64,
 62,
 61,
 58,
 59,
 64,
 64,
 63,
 65,
 56,
 61,
 55,
 56,
 61,
 63,
 61,
 56,
 59,
 58,
 57,
 60,
 63,
 62,
 56,
 60,
 61,
 59,
 60,
 56,
 58,
 63,
 63,
 63,
 58,
 64,
 64,
 64,
 61,
 60,
 56,
 57,
 57,
 65,
 59,
 57,
 64,
 65,
 64,
 62,
 64,
 55,
 57,
 62,
 55,
 59,
 55,
 62,
 61,
 61,
 59,
 55,
 59,
 60,
 60,
 62,
 65,
 61,
 60,
 62,
 58,
 58,
 61,
 60,
 60,
 56,
 58,
 64,
 60,
 63,
 57,
 56,
 58,
 61,
 59,
 62,
 57,
 59,
 58,
 63,
 64,
 59,
 64,
 55,
 65,
 64,
 63,
 65,
 64,
 63,
 62,
 55,
 58,
 65,
 63,
 56,
 61,
 62,
 65,
 61,
 57,
 59,
 57,
 64,
 65,
 64,
 65,
 55,
 55,
 58,
 65,
 63,
 60,
 64,
 65,
 57,
 59,
 58,
 63,
 61,
 55,
 63,
 56,
 62,
 61,
 65,
 59,
 59,
 61,
 56,
 60,
 55,
 64,
 58,
 64,
 57,
 58,
 62,
 56,
 59,
 60,
 63,
 62,
 55,
 64,
 64,
 58,
 57,
 63,
 63,
 63,
 59,
 59,
 63,
 57,
 57,
 60,
 64,
 59,
 60,
 64,
 64,
 64,
 65,
 64,
 56,
 64,
 64,
 62,
 60,
 65,
 60,
 61,
 60,
 58,
 62,
 62,
 57,
 65,
 59,
 58,
 57,
 59,
 64,
 58,
 62,
 65,
 56,
 56,
 63,
 59,
 58,
 61,
 56,
 65,
 65,
 56,
 58,
 64,
 62,
 59,
 59,
 64,
 61,
 59,
 63,
 63,
 64,
 61,
 57,
 60,
 59,
 58,
 62,
 64,
 63,
 58,
 65,
 56,
 57,
 59,
 60,
 61,
 56,
 62,
 65,
 63,
 55,
 65,
 55,
 60,
 58,
 64,
 58,
 60,
 61,
 64,
 63,
 61,
 59,
 55,
 56,
 56,
 65,
 63,
 59,
 63,
 57,
 61,
 59,
 61,
 55,
 65,
 56,
 58,
 64,
 60,
 61,
 56,
 58,
 57,
 56,
 64,
 62,
 64,
 63,
 64,
 57,
 61,
 57,
 60,
 64,
 60,
 55,
 63,
 56,
 60,
 57,
 58,
 60,
 56,
 63,
 64,
 55,
 56,
 65,
 57,
 64,
 60,
 59,
 59,
 58,
 58,
 64,
 64,
 57,
 64,
 57,
 58,
 64,
 56,
 58,
 58,
 63,
 59,
 64,
 65,
 64,
 56,
 63,
 60,
 59,
 59,
 62,
 60,
 64,
 59,
 63,
 61,
 65,
 65,
 64,
 57,
 65,
 58,
 63,
 57,
 59,
 63,
 59,
 55,
 55,
 63,
 65,
 56,
 63,
 58,
 55,
 63,
 65,
 63,
 59,
 55,
 60,
 61,
 58,
 56,
 64,
 61,
 56,
 58,
 58,
 60,
 58,
 59,
 57,
 57,
 55,
 63,
 55,
 58,
 60,
 60,
 56,
 63,
 63,
 59,
 63,
 63,
 63,
 62,
 61,
 62,
 55,
 56,
 57,
 55,
 57,
 55,
 57,
 57,
 57,
 64,
 64,
 56,
 59,
 60,
 61,
 60,
 59,
 63,
 56,
 55,
 62,
 55,
 65,
 63,
 64,
 60,
 55,
 62,
 63,
 58,
 58,
 55,
 59,
 61,
 60,
 60,
 55,
 55,
 57,
 56,
 61,
 59,
 61,
 58,
 60,
 63,
 63,
 55,
 62,
 56,
 63,
 63,
 56,
 65,
 55,
 56,
 59,
 63,
 58,
 61,
 58,
 63,
 56,
 62,
 60,
 59,
 65,
 62,
 65,
 56,
 64,
 57,
 59,
 55,
 65,
 60,
 56,
 59,
 56,
 65,
 63,
 56,
 61,
 55,
 65,
 61,
 59,
 61,
 55,
 60,
 56,
 56,
 60,
 55,
 55,
 60,
 59,
 62,
 63,
 60,
 65,
 61,
 62,
 64,
 60,
 63,
 57,
 63,
 55,
 58,
 59,
 65,
 55,
 58,
 61,
 62,
 64,
 57,
 64,
 55,
 56,
 63,
 58,
 59,
 62,
 59,
 58,
 61,
 58,
 55,
 57,
 61,
 57,
 62,
 59,
 61,
 56,
 58,
 61,
 63,
 58,
 60,
 64,
 60,
 58,
 61,
 55,
 57,
 64,
 58,
 59,
 62,
 56,
 65,
 59,
 58,
 60,
 59,
 55,
 62,
 55,
 57,
 59,
 57,
 63,
 59,
 64,
 55,
 64,
 57,
 64,
 64,
 57,
 60,
 61,
 59,
 60,
 65,
 55,
 62,
 63,
 60,
 61,
 60,
 58,
 58,
 63,
 60,
 57,
 63,
 59,
 59,
 60,
 60,
 63,
 57,
 55,
 55,
 61,
 59,
 60,
 58,
 61,
 64,
 ...]

In [59]:
ok=min(tg)

In [60]:
ok

55

In [61]:
rf['lowerbsalary']=tg

In [62]:
rf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1615940 entries, 0 to 1615939
Data columns (total 27 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   Unnamed: 0        1615940 non-null  int64
 1   Job Id            1615940 non-null  int64
 2   Experience        1615940 non-null  object
 3   Qualifications    1615940 non-null  object
 4   Salary Range      1615940 non-null  object
 5   location          1615940 non-null  object
 6   Country           1615940 non-null  object
 7   latitude          1615940 non-null  float64
 8   longitude         1615940 non-null  float64
 9   Work Type         1615940 non-null  object
 10  Company Size      1615940 non-null  int64
 11  Job Posting Date  1615940 non-null  object
 12  Preference        1615940 non-null  object
 13  Contact Person    1615940 non-null  object
 14  Contact           1615940 non-null  object
 15  Job Title         1615940 non-null  object
 16  Role              1615940 non-null  object
 17  Job Portal        1615940 non-null  object
 18  Job Description   1615940 non-null  object
 19  Benefits          1615940 non-null  object
 20  skills            1615940 non-null  object
 21  Responsibilities  1615940 non-null  object
 22  Company           1615940 non-null  object
 23  Company Profile   1610462 non-null  object
 24  upperbexperience  1615940 non-null  int64
 25  lowerbexperience  1615940 non-null  int64
 26  lowerbsalary      1615940 non-null  int64
dtypes: float64(2), int64(6), object(19)
memory usage: 332.9+ MB

In [63]:
african_countries = [
    'Algeria', 'Angola', 'Benin', 'Botswana', 'Burkina Faso', 'Burundi', 'Cabo Verde',
    'Cameroon', 'Central African Republic', 'Chad', 'Comoros', 'Congo', 'Congo, Democratic Republic of the',
    'Djibouti', 'Egypt', 'Equatorial Guinea', 'Eritrea', 'Eswatini', 'Ethiopia', 'Gabon', 'Gambia', 'Ghana',
    'Guinea', 'Guinea-Bissau', 'Ivory Coast', 'Kenya', 'Lesotho', 'Liberia', 'Libya', 'Madagascar', 'Malawi',
    'Mali', 'Mauritania', 'Mauritius', 'Morocco', 'Mozambique', 'Namibia', 'Niger', 'Nigeria', 'Rwanda',
    'Sao Tome and Principe', 'Senegal', 'Seychelles', 'Sierra Leone', 'Somalia', 'South Africa', 'South Sudan',
    'Sudan', 'Tanzania', 'Togo', 'Tunisia', 'Uganda', 'Zambia', 'Zimbabwe', 'Sahrawi Arab Democratic Republic'
]
# len(african_countries)
asian_countries = [
    "Afghanistan", "Armenia", "Azerbaijan", "Bahrain", "Bangladesh", "Bhutan", "Brunei",
    "Cambodia", "China", "Cyprus", "Georgia", "India", "Indonesia", "Iran", "Iraq",
    "Israel", "Japan", "Jordan", "Kazakhstan", "Kuwait", "Kyrgyzstan", "Laos", "Lebanon",
    "Malaysia", "Maldives", "Mongolia", "Myanmar", "Nepal", "North Korea", "Oman",
    "Pakistan", "Palestine", "Philippines", "Qatar", "Russia", "Saudi Arabia", "Singapore",
    "South Korea", "Sri Lanka", "Syria", "Taiwan", "Tajikistan", "Thailand", "Timor-Leste",
    "Turkey", "Turkmenistan", "United Arab Emirates", "Uzbekistan", "Vietnam", "Yemen"
]

In [64]:
def is_african_country(country):
    return country in african_countries

In [65]:
def is_asian_country(country):
    return country in african_countries

In [66]:
rf['is_african'] = rf['Country'].apply(is_african_country)

In [67]:
rf['is_asian'] = rf['Country'].apply(is_asian_country)

In [68]:
rf['is_african']

0          False
1          False
2          False
3           True
4          False
           ...
1615935     True
1615936    False
1615937    False
1615938     True
1615939     True
Name: is_african, Length: 1615940, dtype: bool

In [69]:
acc=[]
for i in rf['Job Title']:
    if i[0]=='D':
        acc.append(True)
    else:
        acc.append(False)

In [70]:
rf['JobwithD']=acc

In [71]:
rf

,Unnamed: 0,Job Id,Experience,Qualifications,Salary Range,location,Country,latitude,longitude,Work Type,...,skills,Responsibilities,Company,Company Profile,upperbexperience,lowerbexperience,lowerbsalary,is_african,is_asian,JobwithD
0,0,1089843540111562,5 to 15 Years,M.Tech,$59K-$99K,Douglas,Isle of Man,54.2361,-4.5481,Intern,...,"Social media platforms (e.g., Facebook, Twitte...","Manage and grow social media accounts, create ...",Icahn Enterprises,"{""Sector"":""Diversified"",""Industry"":""Diversifie...",15,5,59,False,False,True
1,1,398454096642776,2 to 12 Years,BCA,$56K-$116K,Ashgabat,Turkmenistan,38.9697,59.5563,Intern,...,"HTML, CSS, JavaScript Frontend frameworks (e.g...","Design and code user interfaces for websites, ...",PNC Financial Services Group,"{""Sector"":""Financial Services"",""Industry"":""Com...",12,2,56,False,False,False
2,2,481640072963533,0 to 12 Years,PhD,$61K-$104K,Macao,"Macao SAR, China",22.1987,113.5439,Temporary,...,Quality control processes and methodologies St...,Establish and enforce quality control standard...,United Services Automobile Assn.,"{""Sector"":""Insurance"",""Industry"":""Insurance: P...",12,0,61,False,False,False
3,3,688192671473044,4 to 11 Years,PhD,$65K-$91K,Porto-Novo,Benin,9.3077,2.3158,Full-Time,...,Wireless network design and architecture Wi-Fi...,"Design, configure, and optimize wireless netwo...",Hess,"{""Sector"":""Energy"",""Industry"":""Mining, Crude-O...",11,4,65,True,True,False
4,4,117057806156508,1 to 12 Years,MBA,$64K-$87K,Santiago,Chile,-35.6751,-71.5429,Intern,...,Event planning Conference logistics Budget man...,Specialize in conference and convention planni...,Cairn Energy,"{""Sector"":""Energy"",""Industry"":""Energy - Oil & ...",12,1,64,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1615935,1615935,134563577088850,0 to 12 Years,B.Tech,$64K-$114K,"Malabo (de jure),",Equatorial Guinea,1.6508,10.2679,Full-Time,...,"Mechanical engineering CAD software (e.g., Sol...","Design mechanical systems, components, and pro...",The Hershey Company,"{""Sector"":""Food and Beverage/Confectionery"",""I...",12,0,64,True,True,False
1615936,1615936,618604818190827,2 to 14 Years,M.Tech,$62K-$130K,Warsaw,Poland,51.9194,19.1451,Intern,...,Strategic IT planning Leadership and managemen...,Provide strategic leadership for IT department...,EQT,"{""Sector"":""Energy"",""Industry"":""Energy"",""City"":...",14,2,62,False,False,False
1615937,1615937,615471367712200,4 to 15 Years,BCA,$60K-$96K,Ashgabat,Turkmenistan,38.9697,59.5563,Part-Time,...,"Mechanical engineering CAD software (e.g., Sol...","Design mechanical systems, components, and pro...",KLA,"{""Sector"":""Technology"",""Industry"":""Semiconduct...",15,4,60,False,False,False
1615938,1615938,804137342023945,5 to 15 Years,BCA,$65K-$103K,Ouagadougou,Burkina Faso,12.2383,-1.5616,Full-Time,...,Training program coordination Training materia...,"Coordinate employee training programs, track t...",Mahindra & Mahindra,"{""Sector"":""Automotive"",""Industry"":""Automotive""...",15,5,65,True,True,False
1615939,1615939,404645755314484,1 to 11 Years,BBA,$56K-$109K,Asmara,Eritrea,15.1794,39.7823,Part-Time,...,Wedding planning Venue selection Catering and ...,"Specialize in wedding planning, assisting coup...",Ashtead Group,"{""Sector"":""Equipment Rental"",""Industry"":""Equip...",11,1,56,True,True,False

In [72]:
acc=[]
for i in rf['Contact Person']:
    if i[0]=='D':
        acc.append(True)
    else:
        acc.append(False)

In [73]:
rf['contactA']=acc

In [74]:
rf

,Unnamed: 0,Job Id,Experience,Qualifications,Salary Range,location,Country,latitude,longitude,Work Type,...,Responsibilities,Company,Company Profile,upperbexperience,lowerbexperience,lowerbsalary,is_african,is_asian,JobwithD,contactA
0,0,1089843540111562,5 to 15 Years,M.Tech,$59K-$99K,Douglas,Isle of Man,54.2361,-4.5481,Intern,...,"Manage and grow social media accounts, create ...",Icahn Enterprises,"{""Sector"":""Diversified"",""Industry"":""Diversifie...",15,5,59,False,False,True,False
1,1,398454096642776,2 to 12 Years,BCA,$56K-$116K,Ashgabat,Turkmenistan,38.9697,59.5563,Intern,...,"Design and code user interfaces for websites, ...",PNC Financial Services Group,"{""Sector"":""Financial Services"",""Industry"":""Com...",12,2,56,False,False,False,False
2,2,481640072963533,0 to 12 Years,PhD,$61K-$104K,Macao,"Macao SAR, China",22.1987,113.5439,Temporary,...,Establish and enforce quality control standard...,United Services Automobile Assn.,"{""Sector"":""Insurance"",""Industry"":""Insurance: P...",12,0,61,False,False,False,False
3,3,688192671473044,4 to 11 Years,PhD,$65K-$91K,Porto-Novo,Benin,9.3077,2.3158,Full-Time,...,"Design, configure, and optimize wireless netwo...",Hess,"{""Sector"":""Energy"",""Industry"":""Mining, Crude-O...",11,4,65,True,True,False,False
4,4,117057806156508,1 to 12 Years,MBA,$64K-$87K,Santiago,Chile,-35.6751,-71.5429,Intern,...,Specialize in conference and convention planni...,Cairn Energy,"{""Sector"":""Energy"",""Industry"":""Energy - Oil & ...",12,1,64,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1615935,1615935,134563577088850,0 to 12 Years,B.Tech,$64K-$114K,"Malabo (de jure),",Equatorial Guinea,1.6508,10.2679,Full-Time,...,"Design mechanical systems, components, and pro...",The Hershey Company,"{""Sector"":""Food and Beverage/Confectionery"",""I...",12,0,64,True,True,False,False
1615936,1615936,618604818190827,2 to 14 Years,M.Tech,$62K-$130K,Warsaw,Poland,51.9194,19.1451,Intern,...,Provide strategic leadership for IT department...,EQT,"{""Sector"":""Energy"",""Industry"":""Energy"",""City"":...",14,2,62,False,False,False,False
1615937,1615937,615471367712200,4 to 15 Years,BCA,$60K-$96K,Ashgabat,Turkmenistan,38.9697,59.5563,Part-Time,...,"Design mechanical systems, components, and pro...",KLA,"{""Sector"":""Technology"",""Industry"":""Semiconduct...",15,4,60,False,False,False,False
1615938,1615938,804137342023945,5 to 15 Years,BCA,$65K-$103K,Ouagadougou,Burkina Faso,12.2383,-1.5616,Full-Time,...,"Coordinate employee training programs, track t...",Mahindra & Mahindra,"{""Sector"":""Automotive"",""Industry"":""Automotive""...",15,5,65,True,True,False,False
1615939,1615939,404645755314484,1 to 11 Years,BBA,$56K-$109K,Asmara,Eritrea,15.1794,39.7823,Part-Time,...,"Specialize in wedding planning, assisting coup...",Ashtead Group,"{""Sector"":""Equipment Rental"",""Industry"":""Equip...",11,1,56,True,True,False,False

In [75]:
# acc

In [82]:
t=file['Salary Range'].str.split('-')
tg=[]
for i in t:
    # print(i)
    tg.append(i[1])
# print(t)
# print(tg)
for i in range(len(tg)):
    tg[i]=int(tg[i][1:-1])
# tg

In [84]:
tg

[99,
 116,
 104,
 91,
 87,
 93,
 103,
 102,
 102,
 80,
 104,
 98,
 122,
 86,
 98,
 100,
 83,
 117,
 121,
 128,
 120,
 98,
 116,
 124,
 104,
 107,
 88,
 100,
 86,
 119,
 83,
 115,
 121,
 82,
 130,
 129,
 89,
 103,
 100,
 81,
 109,
 121,
 129,
 95,
 82,
 80,
 109,
 130,
 89,
 97,
 127,
 105,
 123,
 114,
 92,
 102,
 109,
 125,
 88,
 117,
 111,
 125,
 94,
 121,
 84,
 96,
 101,
 114,
 82,
 125,
 83,
 88,
 128,
 88,
 82,
 113,
 87,
 101,
 102,
 121,
 105,
 93,
 96,
 83,
 104,
 113,
 107,
 91,
 128,
 82,
 115,
 113,
 83,
 103,
 83,
 106,
 126,
 121,
 81,
 108,
 85,
 118,
 129,
 94,
 113,
 105,
 86,
 116,
 94,
 89,
 94,
 95,
 95,
 112,
 122,
 107,
 83,
 113,
 96,
 124,
 130,
 127,
 113,
 129,
 107,
 100,
 124,
 88,
 102,
 125,
 111,
 113,
 90,
 104,
 107,
 122,
 128,
 98,
 92,
 126,
 116,
 98,
 129,
 108,
 106,
 95,
 87,
 107,
 97,
 81,
 127,
 125,
 126,
 98,
 101,
 89,
 117,
 128,
 96,
 123,
 112,
 123,
 120,
 114,
 105,
 100,
 98,
 85,
 114,
 109,
 106,
 120,
 82,
 113,
 115,
 125,
 107,
 126,
 117,
 98,
 117,
 129,
 108,
 130,
 101,
 120,
 94,
 100,
 100,
 93,
 104,
 118,
 109,
 112,
 95,
 84,
 98,
 109,
 82,
 99,
 110,
 122,
 105,
 93,
 109,
 122,
 125,
 100,
 93,
 90,
 115,
 89,
 84,
 115,
 111,
 95,
 101,
 82,
 119,
 115,
 90,
 87,
 129,
 116,
 84,
 104,
 110,
 89,
 125,
 87,
 101,
 99,
 102,
 111,
 102,
 114,
 127,
 105,
 119,
 107,
 116,
 106,
 83,
 102,
 121,
 119,
 98,
 119,
 93,
 116,
 111,
 100,
 94,
 103,
 105,
 119,
 81,
 104,
 111,
 106,
 101,
 104,
 82,
 109,
 129,
 115,
 127,
 81,
 121,
 86,
 117,
 121,
 121,
 113,
 92,
 106,
 87,
 89,
 99,
 120,
 97,
 124,
 110,
 99,
 99,
 114,
 87,
 102,
 109,
 80,
 130,
 107,
 95,
 108,
 98,
 100,
 111,
 84,
 126,
 91,
 130,
 92,
 106,
 110,
 102,
 116,
 123,
 120,
 92,
 107,
 81,
 112,
 109,
 90,
 103,
 86,
 81,
 100,
 102,
 100,
 83,
 82,
 108,
 89,
 126,
 123,
 115,
 111,
 111,
 84,
 95,
 86,
 117,
 121,
 88,
 110,
 102,
 126,
 114,
 84,
 110,
 103,
 108,
 96,
 109,
 82,
 94,
 116,
 92,
 129,
 119,
 112,
 113,
 126,
 118,
 81,
 81,
 92,
 88,
 101,
 125,
 88,
 115,
 82,
 85,
 110,
 109,
 90,
 109,
 101,
 129,
 92,
 105,
 104,
 119,
 109,
 117,
 83,
 118,
 100,
 92,
 113,
 95,
 122,
 130,
 88,
 118,
 124,
 81,
 118,
 100,
 92,
 113,
 81,
 93,
 110,
 114,
 116,
 98,
 117,
 93,
 99,
 101,
 120,
 90,
 130,
 105,
 106,
 105,
 129,
 88,
 95,
 95,
 83,
 114,
 84,
 84,
 102,
 128,
 96,
 98,
 97,
 91,
 119,
 120,
 83,
 117,
 99,
 128,
 116,
 107,
 93,
 106,
 88,
 112,
 85,
 99,
 91,
 117,
 87,
 97,
 128,
 114,
 124,
 123,
 90,
 82,
 104,
 94,
 104,
 109,
 117,
 102,
 102,
 100,
 89,
 116,
 89,
 84,
 99,
 104,
 125,
 124,
 123,
 117,
 82,
 90,
 126,
 83,
 83,
 125,
 120,
 95,
 111,
 105,
 114,
 106,
 87,
 104,
 91,
 112,
 127,
 117,
 122,
 128,
 126,
 84,
 80,
 80,
 106,
 113,
 106,
 99,
 89,
 113,
 97,
 111,
 92,
 114,
 106,
 85,
 129,
 101,
 100,
 111,
 112,
 127,
 98,
 97,
 129,
 89,
 113,
 117,
 125,
 102,
 102,
 120,
 99,
 111,
 85,
 129,
 80,
 89,
 116,
 118,
 125,
 83,
 107,
 87,
 99,
 129,
 108,
 107,
 83,
 85,
 128,
 106,
 86,
 101,
 84,
 118,
 85,
 101,
 80,
 122,
 97,
 123,
 86,
 92,
 111,
 106,
 118,
 115,
 84,
 109,
 113,
 105,
 92,
 121,
 88,
 101,
 124,
 92,
 104,
 82,
 103,
 103,
 119,
 116,
 92,
 95,
 123,
 90,
 113,
 124,
 103,
 102,
 98,
 95,
 118,
 102,
 109,
 119,
 88,
 123,
 102,
 120,
 97,
 107,
 126,
 81,
 100,
 96,
 89,
 86,
 94,
 85,
 122,
 104,
 102,
 82,
 121,
 114,
 82,
 102,
 105,
 91,
 118,
 82,
 107,
 112,
 127,
 94,
 82,
 100,
 114,
 107,
 115,
 98,
 120,
 116,
 89,
 92,
 123,
 95,
 103,
 97,
 98,
 101,
 105,
 82,
 91,
 90,
 97,
 98,
 87,
 97,
 92,
 117,
 113,
 80,
 80,
 120,
 93,
 88,
 109,
 82,
 125,
 115,
 128,
 121,
 128,
 125,
 91,
 101,
 99,
 112,
 100,
 93,
 95,
 81,
 99,
 114,
 87,
 115,
 117,
 81,
 87,
 104,
 116,
 107,
 103,
 90,
 130,
 124,
 111,
 121,
 128,
 91,
 93,
 113,
 118,
 128,
 99,
 128,
 105,
 118,
 81,
 89,
 85,
 118,
 85,
 85,
 129,
 108,
 129,
 109,
 107,
 123,
 94,
 105,
 125,
 83,
 80,
 93,
 98,
 105,
 120,
 110,
 104,
 127,
 129,
 130,
 112,
 80,
 124,
 81,
 84,
 118,
 91,
 102,
 114,
 89,
 109,
 83,
 108,
 86,
 114,
 92,
 98,
 99,
 80,
 128,
 102,
 106,
 89,
 106,
 122,
 116,
 88,
 106,
 92,
 81,
 105,
 94,
 118,
 106,
 103,
 80,
 83,
 112,
 95,
 93,
 111,
 94,
 88,
 116,
 82,
 82,
 86,
 80,
 113,
 101,
 111,
 114,
 82,
 108,
 124,
 119,
 88,
 129,
 88,
 112,
 102,
 115,
 116,
 81,
 81,
 90,
 102,
 80,
 82,
 119,
 100,
 105,
 84,
 117,
 85,
 125,
 118,
 102,
 115,
 92,
 119,
 99,
 117,
 106,
 81,
 90,
 90,
 92,
 111,
 126,
 120,
 109,
 127,
 106,
 85,
 126,
 129,
 118,
 105,
 84,
 81,
 89,
 125,
 120,
 127,
 81,
 95,
 116,
 87,
 93,
 119,
 127,
 116,
 111,
 88,
 129,
 124,
 85,
 95,
 130,
 102,
 117,
 102,
 113,
 119,
 109,
 114,
 86,
 83,
 92,
 85,
 80,
 116,
 86,
 108,
 91,
 84,
 98,
 103,
 111,
 121,
 81,
 97,
 91,
 102,
 121,
 86,
 103,
 128,
 102,
 129,
 121,
 120,
 119,
 86,
 96,
 91,
 121,
 122,
 82,
 111,
 100,
 117,
 121,
 90,
 107,
 129,
 125,
 107,
 107,
 114,
 112,
 111,
 126,
 106,
 98,
 111,
 83,
 105,
 130,
 129,
 101,
 92,
 102,
 129,
 89,
 81,
 84,
 116,
 105,
 122,
 111,
 101,
 108,
 82,
 107,
 120,
 130,
 112,
 81,
 104,
 124,
 85,
 113,
 86,
 125,
 104,
 130,
 113,
 122,
 104,
 96,
 128,
 114,
 113,
 95,
 100,
 123,
 127,
 122,
 91,
 113,
 85,
 127,
 94,
 96,
 120,
 107,
 115,
 100,
 113,
 105,
 118,
 101,
 120,
 90,
 126,
 113,
 85,
 110,
 124,
 116,
 100,
 93,
 105,
 90,
 125,
 114,
 127,
 129,
 107,
 98,
 82,
 127,
 130,
 87,
 113,
 122,
 110,
 113,
 105,
 98,
 125,
 96,
 80,
 101,
 92,
 80,
 102,
 91,
 123,
 113,
 102,
 101,
 94,
 89,
 128,
 128,
 103,
 116,
 99,
 123,
 117,
 104,
 113,
 128,
 118,
 ...]

In [85]:
rf['upperbsalary']=tg

In [86]:
rf['salaryrange']=rf['upperbsalary']-rf['lowerbsalary']

In [87]:
rf

,Unnamed: 0,Job Id,Experience,Qualifications,Salary Range,location,Country,latitude,longitude,Work Type,...,Company Profile,upperbexperience,lowerbexperience,lowerbsalary,is_african,is_asian,JobwithD,contactA,upperbsalary,salaryrange
0,0,1089843540111562,5 to 15 Years,M.Tech,$59K-$99K,Douglas,Isle of Man,54.2361,-4.5481,Intern,...,"{""Sector"":""Diversified"",""Industry"":""Diversifie...",15,5,59,False,False,True,False,99,40
1,1,398454096642776,2 to 12 Years,BCA,$56K-$116K,Ashgabat,Turkmenistan,38.9697,59.5563,Intern,...,"{""Sector"":""Financial Services"",""Industry"":""Com...",12,2,56,False,False,False,False,116,60
2,2,481640072963533,0 to 12 Years,PhD,$61K-$104K,Macao,"Macao SAR, China",22.1987,113.5439,Temporary,...,"{""Sector"":""Insurance"",""Industry"":""Insurance: P...",12,0,61,False,False,False,False,104,43
3,3,688192671473044,4 to 11 Years,PhD,$65K-$91K,Porto-Novo,Benin,9.3077,2.3158,Full-Time,...,"{""Sector"":""Energy"",""Industry"":""Mining, Crude-O...",11,4,65,True,True,False,False,91,26
4,4,117057806156508,1 to 12 Years,MBA,$64K-$87K,Santiago,Chile,-35.6751,-71.5429,Intern,...,"{""Sector"":""Energy"",""Industry"":""Energy - Oil & ...",12,1,64,False,False,False,False,87,23
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1615935,1615935,134563577088850,0 to 12 Years,B.Tech,$64K-$114K,"Malabo (de jure),",Equatorial Guinea,1.6508,10.2679,Full-Time,...,"{""Sector"":""Food and Beverage/Confectionery"",""I...",12,0,64,True,True,False,False,114,50
1615936,1615936,618604818190827,2 to 14 Years,M.Tech,$62K-$130K,Warsaw,Poland,51.9194,19.1451,Intern,...,"{""Sector"":""Energy"",""Industry"":""Energy"",""City"":...",14,2,62,False,False,False,False,130,68
1615937,1615937,615471367712200,4 to 15 Years,BCA,$60K-$96K,Ashgabat,Turkmenistan,38.9697,59.5563,Part-Time,...,"{""Sector"":""Technology"",""Industry"":""Semiconduct...",15,4,60,False,False,False,False,96,36
1615938,1615938,804137342023945,5 to 15 Years,BCA,$65K-$103K,Ouagadougou,Burkina Faso,12.2383,-1.5616,Full-Time,...,"{""Sector"":""Automotive"",""Industry"":""Automotive""...",15,5,65,True,True,False,False,103,38
1615939,1615939,404645755314484,1 to 11 Years,BBA,$56K-$109K,Asmara,Eritrea,15.1794,39.7823,Part-Time,...,"{""Sector"":""Equipment Rental"",""Industry"":""Equip...",11,1,56,True,True,False,False,109,53

In [88]:
max(rf['salaryrange'])

75

In [89]:
rf.to_csv('jobdata2.csv')

In [90]:
rf=pd.read_csv('jobdata2.csv')
rf

,Unnamed: 0.1,Unnamed: 0,Job Id,Experience,Qualifications,Salary Range,location,Country,latitude,longitude,...,Company Profile,upperbexperience,lowerbexperience,lowerbsalary,is_african,is_asian,JobwithD,contactA,upperbsalary,salaryrange
0,0,0,1089843540111562,5 to 15 Years,M.Tech,$59K-$99K,Douglas,Isle of Man,54.2361,-4.5481,...,"{""Sector"":""Diversified"",""Industry"":""Diversifie...",15,5,59,False,False,True,False,99,40
1,1,1,398454096642776,2 to 12 Years,BCA,$56K-$116K,Ashgabat,Turkmenistan,38.9697,59.5563,...,"{""Sector"":""Financial Services"",""Industry"":""Com...",12,2,56,False,False,False,False,116,60
2,2,2,481640072963533,0 to 12 Years,PhD,$61K-$104K,Macao,"Macao SAR, China",22.1987,113.5439,...,"{""Sector"":""Insurance"",""Industry"":""Insurance: P...",12,0,61,False,False,False,False,104,43
3,3,3,688192671473044,4 to 11 Years,PhD,$65K-$91K,Porto-Novo,Benin,9.3077,2.3158,...,"{""Sector"":""Energy"",""Industry"":""Mining, Crude-O...",11,4,65,True,True,False,False,91,26
4,4,4,117057806156508,1 to 12 Years,MBA,$64K-$87K,Santiago,Chile,-35.6751,-71.5429,...,"{""Sector"":""Energy"",""Industry"":""Energy - Oil & ...",12,1,64,False,False,False,False,87,23
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1615935,1615935,1615935,134563577088850,0 to 12 Years,B.Tech,$64K-$114K,"Malabo (de jure),",Equatorial Guinea,1.6508,10.2679,...,"{""Sector"":""Food and Beverage/Confectionery"",""I...",12,0,64,True,True,False,False,114,50
1615936,1615936,1615936,618604818190827,2 to 14 Years,M.Tech,$62K-$130K,Warsaw,Poland,51.9194,19.1451,...,"{""Sector"":""Energy"",""Industry"":""Energy"",""City"":...",14,2,62,False,False,False,False,130,68
1615937,1615937,1615937,615471367712200,4 to 15 Years,BCA,$60K-$96K,Ashgabat,Turkmenistan,38.9697,59.5563,...,"{""Sector"":""Technology"",""Industry"":""Semiconduct...",15,4,60,False,False,False,False,96,36
1615938,1615938,1615938,804137342023945,5 to 15 Years,BCA,$65K-$103K,Ouagadougou,Burkina Faso,12.2383,-1.5616,...,"{""Sector"":""Automotive"",""Industry"":""Automotive""...",15,5,65,True,True,False,False,103,38
1615939,1615939,1615939,404645755314484,1 to 11 Years,BBA,$56K-$109K,Asmara,Eritrea,15.1794,39.7823,...,"{""Sector"":""Equipment Rental"",""Industry"":""Equip...",11,1,56,True,True,False,False,109,53